sudo: false
language: ruby
rvm:
  - 2.2.1

bundler_args: --path=vendor/bundle --without heroku

cache: bundler

before_script:
  - sh -c "psql -c 'create database fat_free_crm_test;' -U postgres"
  - sh -c "RAILS_ENV=test bundle exec rake db:schema:load"

# Run specs
script: "bundle exec rake"
